services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=${var_dbPassword}'
      - 'POSTGRES_USER=${var_dbUsername}'
    ports:
      - '5432:5432'
    restart: always
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_POST: 5050
    ports:
      - '5050:80'
    restart: always
