spring:
  application:
    name:
      fastfile-be
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: ${var_dbUsername}
    password: ${var_dbPassword}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}

server:
  port: 8080
  address: 0.0.0.0
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: ${var_keystorePass}
    key-alias: jakubpiskorzSSL
    enabled: true
    key-store-type: JKS



management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

